### PR TITLE
Support sending heic images

### PR DESCRIPTION
**Pull request by raphaelcastaneda**
Implements feature request mautrix/whatsapp#635 by converting heic files to jpeg before attaching to a message

### CODE REVIEW

**Comment by tulir** [comment]
That library looks unmaintained and doesn't work on arm/arm64. The amount of C code in general should also be minimized, I don't think there are any Go heif decoders.

**Comment by raphaelcastaneda** [comment]
There appears to be a fork of that library that does have arm support, but I'm not sure whether it's worth pursuing that.

**Comment by kinduff** [comment]
@raphaelcastaneda Maybe https://github.com/klippa-app/go-libheif could work

**Comment by raphaelcastaneda** [comment]
> @raphaelcastaneda Maybe [klippa-app/go-libheif](https://github.com/klippa-app/go-libheif) could work

This is a (really thin) wrapper around the much more active library: https://github.com/strukturag/libheif, so I'd opt to use that directly instead.

I think it's a question for @tulir whether usage of that library here is acceptable. This library is also based on a C implementation, but at least the underlying library (https://github.com/strukturag/libde265) appears to have arm support.

**Comment by niebloomj** [comment]
Why do we want the bridge to support a file type that whatsapp doesn't?

**Comment by niebloomj** [comment]
Makes sense 👍

**Pull request closed without merging**
