### PR TITLE
Always add URL field on media events

### PR DESCRIPTION
**Pull request by surakin**
Fixes https://github.com/mautrix/whatsapp/issues/662 
Fixes https://github.com/element-hq/element-x-ios/issues/1047

### CODE REVIEW

**Comment by sumnerevans** [comment]
Are stickers not supposed to be encrypted by the spec :scream:

**Comment by jjj333-p** [comment]
> Are stickers not supposed to be encrypted by the spec 😱

as far as i understand the spec completely ignores this possibility.

i think it makes sense from a userland implementation, you add it to the global im.ponies.emotes or whatever state event as an mxc and then you just link to it and its intended to be a public resource. the difference is that the bridge treats stickers as media to bridge and therefore tries to encrypt it which simply doesnt agree with that thought train. i suppose its just a hole in the spec

**Review by tulir — CHANGES_REQUESTED** [review]
Workarounds for bad clients need to be clearly marked. It also needs to be minimal, like using a fake mxc URI or a blank string to avoid it being misinterpreted as a real field. Definitely can't add it to non-sticker events either

**Comment by surakin** [comment]
As far as I understand the issue, the rust sdk uses the url field when it parses a sticker so it can't be fake or blank.

**Comment by tulir** [comment]
It must also be using the `file` object, because otherwise it'd just get an encrypted blob. That's why I assumed it was only validating the presence of `url` and not actually using it

**Comment by surakin** [comment]
> It must also be using the `file` object, because otherwise it'd just get an encrypted blob. That's why I assumed it was only validating the presence of `url` and not actually using it

I just tried using an empty string and stickers don't show up
It must be using the file object, yes, but the missing url makes the initial parsing of the sticker event just fail

**Comment by jjj333-p** [comment]
It’s got to be using the keys from the file object, it’s probably a bug in
the sdk

**Comment by surakin** [comment]
> It’s got to be using the keys from the file object, it’s probably a bug in the sdk
More like a bug in the spec, I think. It says that for stickers the content.url field is required and the sdk is honoring that :shrug:

**Comment by tulir** [comment]
Hmm, I can't reproduce making element x work by just adding the url field

**Comment by surakin** [comment]
Are you running latest from the develop branch?
- *M*arco

**Comment by tulir** [comment]
Yes, it tries to render it, but just shows a blank box

**Comment by surakin** [comment]
Closing in favor of https://github.com/ruma/ruma/pull/1820

**Pull request closed without merging**
